export const countryList = [
  {
    name: 'Afghanistan',
    numeric_code: '004',
    phone_code: '93',
    region_id: '3',
    value: 'AF',
  },
  {
    name: 'Aland Islands',
    numeric_code: '248',
    phone_code: '+358-18',
    region_id: '4',
    value: 'AX',
  },
  {
    name: 'Albania',
    numeric_code: '008',
    phone_code: '355',
    region_id: '4',
    value: 'AL',
  },
  {
    name: 'Algeria',
    numeric_code: '012',
    phone_code: '213',
    region_id: '1',
    value: 'DZ',
  },
  {
    name: 'American Samoa',
    numeric_code: '016',
    phone_code: '+1-684',
    region_id: '5',
    value: 'AS',
  },
  {
    name: 'Andorra',
    numeric_code: '020',
    phone_code: '376',
    region_id: '4',
    value: 'AD',
  },
  {
    name: 'Angola',
    numeric_code: '024',
    phone_code: '244',
    region_id: '1',
    value: 'AO',
  },
  {
    name: 'Anguilla',
    numeric_code: '660',
    phone_code: '+1-264',
    region_id: '2',
    value: 'AI',
  },
  {
    name: 'Antarctica',
    numeric_code: '010',
    phone_code: '672',
    region_id: '6',
    value: 'AQ',
  },
  {
    name: 'Antigua and Barbuda',
    numeric_code: '028',
    phone_code: '+1-268',
    region_id: '2',
    value: 'AG',
  },
  {
    name: 'Argentina',
    numeric_code: '032',
    phone_code: '54',
    region_id: '2',
    value: 'AR',
  },
  {
    name: 'Armenia',
    numeric_code: '051',
    phone_code: '374',
    region_id: '3',
    value: 'AM',
  },
  {
    name: 'Aruba',
    numeric_code: '533',
    phone_code: '297',
    region_id: '2',
    value: 'AW',
  },
  {
    name: 'Australia',
    numeric_code: '036',
    phone_code: '61',
    region_id: '5',
    value: 'AU',
  },
  {
    name: 'Austria',
    numeric_code: '040',
    phone_code: '43',
    region_id: '4',
    value: 'AT',
  },
  {
    name: 'Azerbaijan',
    numeric_code: '031',
    phone_code: '994',
    region_id: '3',
    value: 'AZ',
  },
  {
    name: 'Bahrain',
    numeric_code: '048',
    phone_code: '973',
    region_id: '3',
    value: 'BH',
  },
  {
    name: 'Bangladesh',
    numeric_code: '050',
    phone_code: '880',
    region_id: '3',
    value: 'BD',
  },
  {
    name: 'Barbados',
    numeric_code: '052',
    phone_code: '+1-246',
    region_id: '2',
    value: 'BB',
  },
  {
    name: 'Belarus',
    numeric_code: '112',
    phone_code: '375',
    region_id: '4',
    value: 'BY',
  },
  {
    name: 'Belgium',
    numeric_code: '056',
    phone_code: '32',
    region_id: '4',
    value: 'BE',
  },
  {
    name: 'Belize',
    numeric_code: '084',
    phone_code: '501',
    region_id: '2',
    value: 'BZ',
  },
  {
    name: 'Benin',
    numeric_code: '204',
    phone_code: '229',
    region_id: '1',
    value: 'BJ',
  },
  {
    name: 'Bermuda',
    numeric_code: '060',
    phone_code: '+1-441',
    region_id: '2',
    value: 'BM',
  },
  {
    name: 'Bhutan',
    numeric_code: '064',
    phone_code: '975',
    region_id: '3',
    value: 'BT',
  },
  {
    name: 'Bolivia',
    numeric_code: '068',
    phone_code: '591',
    region_id: '2',
    value: 'BO',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    numeric_code: '535',
    phone_code: '599',
    region_id: '2',
    value: 'BQ',
  },
  {
    name: 'Bosnia and Herzegovina',
    numeric_code: '070',
    phone_code: '387',
    region_id: '4',
    value: 'BA',
  },
  {
    name: 'Botswana',
    numeric_code: '072',
    phone_code: '267',
    region_id: '1',
    value: 'BW',
  },
  {
    name: 'Bouvet Island',
    numeric_code: '074',
    phone_code: '0055',
    region_id: null,
    value: 'BV',
  },
  {
    name: 'Brazil',
    numeric_code: '076',
    phone_code: '55',
    region_id: '2',
    value: 'BR',
  },
  {
    name: 'British Indian Ocean Territory',
    numeric_code: '086',
    phone_code: '246',
    region_id: '1',
    value: 'IO',
  },
  {
    name: 'Brunei',
    numeric_code: '096',
    phone_code: '673',
    region_id: '3',
    value: 'BN',
  },
  {
    name: 'Bulgaria',
    numeric_code: '100',
    phone_code: '359',
    region_id: '4',
    value: 'BG',
  },
  {
    name: 'Burkina Faso',
    numeric_code: '854',
    phone_code: '226',
    region_id: '1',
    value: 'BF',
  },
  {
    name: 'Burundi',
    numeric_code: '108',
    phone_code: '257',
    region_id: '1',
    value: 'BI',
  },
  {
    name: 'Cambodia',
    numeric_code: '116',
    phone_code: '855',
    region_id: '3',
    value: 'KH',
  },
  {
    name: 'Cameroon',
    numeric_code: '120',
    phone_code: '237',
    region_id: '1',
    value: 'CM',
  },
  {
    name: 'Canada',
    numeric_code: '124',
    phone_code: '1',
    region_id: '2',
    value: 'CA',
  },
  {
    name: 'Cape Verde',
    numeric_code: '132',
    phone_code: '238',
    region_id: '1',
    value: 'CV',
  },
  {
    name: 'Cayman Islands',
    numeric_code: '136',
    phone_code: '+1-345',
    region_id: '2',
    value: 'KY',
  },
  {
    name: 'Central African Republic',
    numeric_code: '140',
    phone_code: '236',
    region_id: '1',
    value: 'CF',
  },
  {
    name: 'Chad',
    numeric_code: '148',
    phone_code: '235',
    region_id: '1',
    value: 'TD',
  },
  {
    name: 'Chile',
    numeric_code: '152',
    phone_code: '56',
    region_id: '2',
    value: 'CL',
  },
  {
    name: 'China',
    numeric_code: '156',
    phone_code: '86',
    region_id: '3',
    value: 'CN',
  },
  {
    name: 'Christmas Island',
    numeric_code: '162',
    phone_code: '61',
    region_id: '5',
    value: 'CX',
  },
  {
    name: 'Cocos (Keeling) Islands',
    numeric_code: '166',
    phone_code: '61',
    region_id: '5',
    value: 'CC',
  },
  {
    name: 'Colombia',
    numeric_code: '170',
    phone_code: '57',
    region_id: '2',
    value: 'CO',
  },
  {
    name: 'Comoros',
    numeric_code: '174',
    phone_code: '269',
    region_id: '1',
    value: 'KM',
  },
  {
    name: 'Congo',
    numeric_code: '178',
    phone_code: '242',
    region_id: '1',
    value: 'CG',
  },
  {
    name: 'Cook Islands',
    numeric_code: '184',
    phone_code: '682',
    region_id: '5',
    value: 'CK',
  },
  {
    name: 'Costa Rica',
    numeric_code: '188',
    phone_code: '506',
    region_id: '2',
    value: 'CR',
  },
  {
    name: "Cote D'Ivoire (Ivory Coast)",
    numeric_code: '384',
    phone_code: '225',
    region_id: '1',
    value: 'CI',
  },
  {
    name: 'Croatia',
    numeric_code: '191',
    phone_code: '385',
    region_id: '4',
    value: 'HR',
  },
  {
    name: 'Cuba',
    numeric_code: '192',
    phone_code: '53',
    region_id: '2',
    value: 'CU',
  },
  {
    name: 'Curaçao',
    numeric_code: '531',
    phone_code: '599',
    region_id: '2',
    value: 'CW',
  },
  {
    name: 'Cyprus',
    numeric_code: '196',
    phone_code: '357',
    region_id: '4',
    value: 'CY',
  },
  {
    name: 'Czech Republic',
    numeric_code: '203',
    phone_code: '420',
    region_id: '4',
    value: 'CZ',
  },
  {
    name: 'Democratic Republic of the Congo',
    numeric_code: '180',
    phone_code: '243',
    region_id: '1',
    value: 'CD',
  },
  {
    name: 'Denmark',
    numeric_code: '208',
    phone_code: '45',
    region_id: '4',
    value: 'DK',
  },
  {
    name: 'Djibouti',
    numeric_code: '262',
    phone_code: '253',
    region_id: '1',
    value: 'DJ',
  },
  {
    name: 'Dominica',
    numeric_code: '212',
    phone_code: '+1-767',
    region_id: '2',
    value: 'DM',
  },
  {
    name: 'Dominican Republic',
    numeric_code: '214',
    phone_code: '+1-809 and 1-829',
    region_id: '2',
    value: 'DO',
  },
  {
    name: 'Ecuador',
    numeric_code: '218',
    phone_code: '593',
    region_id: '2',
    value: 'EC',
  },
  {
    name: 'Egypt',
    numeric_code: '818',
    phone_code: '20',
    region_id: '1',
    value: 'EG',
  },
  {
    name: 'El Salvador',
    numeric_code: '222',
    phone_code: '503',
    region_id: '2',
    value: 'SV',
  },
  {
    name: 'Equatorial Guinea',
    numeric_code: '226',
    phone_code: '240',
    region_id: '1',
    value: 'GQ',
  },
  {
    name: 'Eritrea',
    numeric_code: '232',
    phone_code: '291',
    region_id: '1',
    value: 'ER',
  },
  {
    name: 'Estonia',
    numeric_code: '233',
    phone_code: '372',
    region_id: '4',
    value: 'EE',
  },
  {
    name: 'Eswatini',
    numeric_code: '748',
    phone_code: '268',
    region_id: '1',
    value: 'SZ',
  },
  {
    name: 'Ethiopia',
    numeric_code: '231',
    phone_code: '251',
    region_id: '1',
    value: 'ET',
  },
  {
    name: 'Falkland Islands',
    numeric_code: '238',
    phone_code: '500',
    region_id: '2',
    value: 'FK',
  },
  {
    name: 'Faroe Islands',
    numeric_code: '234',
    phone_code: '298',
    region_id: '4',
    value: 'FO',
  },
  {
    name: 'Fiji Islands',
    numeric_code: '242',
    phone_code: '679',
    region_id: '5',
    value: 'FJ',
  },
  {
    name: 'Finland',
    numeric_code: '246',
    phone_code: '358',
    region_id: '4',
    value: 'FI',
  },
  {
    name: 'France',
    numeric_code: '250',
    phone_code: '33',
    region_id: '4',
    value: 'FR',
  },
  {
    name: 'French Guiana',
    numeric_code: '254',
    phone_code: '594',
    region_id: '2',
    value: 'GF',
  },
  {
    name: 'French Polynesia',
    numeric_code: '258',
    phone_code: '689',
    region_id: '5',
    value: 'PF',
  },
  {
    name: 'French Southern Territories',
    numeric_code: '260',
    phone_code: '262',
    region_id: '1',
    value: 'TF',
  },
  {
    name: 'Gabon',
    numeric_code: '266',
    phone_code: '241',
    region_id: '1',
    value: 'GA',
  },
  {
    name: 'Gambia The',
    numeric_code: '270',
    phone_code: '220',
    region_id: '1',
    value: 'GM',
  },
  {
    name: 'Georgia',
    numeric_code: '268',
    phone_code: '995',
    region_id: '3',
    value: 'GE',
  },
  {
    name: 'Germany',
    numeric_code: '276',
    phone_code: '49',
    region_id: '4',
    value: 'DE',
  },
  {
    name: 'Ghana',
    numeric_code: '288',
    phone_code: '233',
    region_id: '1',
    value: 'GH',
  },
  {
    name: 'Gibraltar',
    numeric_code: '292',
    phone_code: '350',
    region_id: '4',
    value: 'GI',
  },
  {
    name: 'Greece',
    numeric_code: '300',
    phone_code: '30',
    region_id: '4',
    value: 'GR',
  },
  {
    name: 'Greenland',
    numeric_code: '304',
    phone_code: '299',
    region_id: '2',
    value: 'GL',
  },
  {
    name: 'Grenada',
    numeric_code: '308',
    phone_code: '+1-473',
    region_id: '2',
    value: 'GD',
  },
  {
    name: 'Guadeloupe',
    numeric_code: '312',
    phone_code: '590',
    region_id: '2',
    value: 'GP',
  },
  {
    name: 'Guam',
    numeric_code: '316',
    phone_code: '+1-671',
    region_id: '5',
    value: 'GU',
  },
  {
    name: 'Guatemala',
    numeric_code: '320',
    phone_code: '502',
    region_id: '2',
    value: 'GT',
  },
  {
    name: 'Guernsey and Alderney',
    numeric_code: '831',
    phone_code: '+44-1481',
    region_id: '4',
    value: 'GG',
  },
  {
    name: 'Guinea',
    numeric_code: '324',
    phone_code: '224',
    region_id: '1',
    value: 'GN',
  },
  {
    name: 'Guinea-Bissau',
    numeric_code: '624',
    phone_code: '245',
    region_id: '1',
    value: 'GW',
  },
  {
    name: 'Guyana',
    numeric_code: '328',
    phone_code: '592',
    region_id: '2',
    value: 'GY',
  },
  {
    name: 'Haiti',
    numeric_code: '332',
    phone_code: '509',
    region_id: '2',
    value: 'HT',
  },
  {
    name: 'Heard Island and McDonald Islands',
    numeric_code: '334',
    phone_code: '672',
    region_id: null,
    value: 'HM',
  },
  {
    name: 'Honduras',
    numeric_code: '340',
    phone_code: '504',
    region_id: '2',
    value: 'HN',
  },
  {
    name: 'Hong Kong S.A.R.',
    numeric_code: '344',
    phone_code: '852',
    region_id: '3',
    value: 'HK',
  },
  {
    name: 'Hungary',
    numeric_code: '348',
    phone_code: '36',
    region_id: '4',
    value: 'HU',
  },
  {
    name: 'Iceland',
    numeric_code: '352',
    phone_code: '354',
    region_id: '4',
    value: 'IS',
  },
  {
    name: 'India',
    numeric_code: '356',
    phone_code: '91',
    region_id: '3',
    value: 'IN',
  },
  {
    name: 'Indonesia',
    numeric_code: '360',
    phone_code: '62',
    region_id: '3',
    value: 'ID',
  },
  {
    name: 'Iran',
    numeric_code: '364',
    phone_code: '98',
    region_id: '3',
    value: 'IR',
  },
  {
    name: 'Iraq',
    numeric_code: '368',
    phone_code: '964',
    region_id: '3',
    value: 'IQ',
  },
  {
    name: 'Ireland',
    numeric_code: '372',
    phone_code: '353',
    region_id: '4',
    value: 'IE',
  },
  {
    name: 'Israel',
    numeric_code: '376',
    phone_code: '972',
    region_id: '3',
    value: 'IL',
  },
  {
    name: 'Italy',
    numeric_code: '380',
    phone_code: '39',
    region_id: '4',
    value: 'IT',
  },
  {
    name: 'Jamaica',
    numeric_code: '388',
    phone_code: '+1-876',
    region_id: '2',
    value: 'JM',
  },
  {
    name: 'Japan',
    numeric_code: '392',
    phone_code: '81',
    region_id: '3',
    value: 'JP',
  },
  {
    name: 'Jersey',
    numeric_code: '832',
    phone_code: '+44-1534',
    region_id: '4',
    value: 'JE',
  },
  {
    name: 'Jordan',
    numeric_code: '400',
    phone_code: '962',
    region_id: '3',
    value: 'JO',
  },
  {
    name: 'Kazakhstan',
    numeric_code: '398',
    phone_code: '7',
    region_id: '3',
    value: 'KZ',
  },
  {
    name: 'Kenya',
    numeric_code: '404',
    phone_code: '254',
    region_id: '1',
    value: 'KE',
  },
  {
    name: 'Kiribati',
    numeric_code: '296',
    phone_code: '686',
    region_id: '5',
    value: 'KI',
  },
  {
    name: 'Kosovo',
    numeric_code: '926',
    phone_code: '383',
    region_id: '4',
    value: 'XK',
  },
  {
    name: 'Kuwait',
    numeric_code: '414',
    phone_code: '965',
    region_id: '3',
    value: 'KW',
  },
  {
    name: 'Kyrgyzstan',
    numeric_code: '417',
    phone_code: '996',
    region_id: '3',
    value: 'KG',
  },
  {
    name: 'Laos',
    numeric_code: '418',
    phone_code: '856',
    region_id: '3',
    value: 'LA',
  },
  {
    name: 'Latvia',
    numeric_code: '428',
    phone_code: '371',
    region_id: '4',
    value: 'LV',
  },
  {
    name: 'Lebanon',
    numeric_code: '422',
    phone_code: '961',
    region_id: '3',
    value: 'LB',
  },
  {
    name: 'Lesotho',
    numeric_code: '426',
    phone_code: '266',
    region_id: '1',
    value: 'LS',
  },
  {
    name: 'Liberia',
    numeric_code: '430',
    phone_code: '231',
    region_id: '1',
    value: 'LR',
  },
  {
    name: 'Libya',
    numeric_code: '434',
    phone_code: '218',
    region_id: '1',
    value: 'LY',
  },
  {
    name: 'Liechtenstein',
    numeric_code: '438',
    phone_code: '423',
    region_id: '4',
    value: 'LI',
  },
  {
    name: 'Lithuania',
    numeric_code: '440',
    phone_code: '370',
    region_id: '4',
    value: 'LT',
  },
  {
    name: 'Luxembourg',
    numeric_code: '442',
    phone_code: '352',
    region_id: '4',
    value: 'LU',
  },
  {
    name: 'Macau S.A.R.',
    numeric_code: '446',
    phone_code: '853',
    region_id: '3',
    value: 'MO',
  },
  {
    name: 'Madagascar',
    numeric_code: '450',
    phone_code: '261',
    region_id: '1',
    value: 'MG',
  },
  {
    name: 'Malawi',
    numeric_code: '454',
    phone_code: '265',
    region_id: '1',
    value: 'MW',
  },
  {
    name: 'Malaysia',
    numeric_code: '458',
    phone_code: '60',
    region_id: '3',
    value: 'MY',
  },
  {
    name: 'Maldives',
    numeric_code: '462',
    phone_code: '960',
    region_id: '3',
    value: 'MV',
  },
  {
    name: 'Mali',
    numeric_code: '466',
    phone_code: '223',
    region_id: '1',
    value: 'ML',
  },
  {
    name: 'Malta',
    numeric_code: '470',
    phone_code: '356',
    region_id: '4',
    value: 'MT',
  },
  {
    name: 'Man (Isle of)',
    numeric_code: '833',
    phone_code: '+44-1624',
    region_id: '4',
    value: 'IM',
  },
  {
    name: 'Marshall Islands',
    numeric_code: '584',
    phone_code: '692',
    region_id: '5',
    value: 'MH',
  },
  {
    name: 'Martinique',
    numeric_code: '474',
    phone_code: '596',
    region_id: '2',
    value: 'MQ',
  },
  {
    name: 'Mauritania',
    numeric_code: '478',
    phone_code: '222',
    region_id: '1',
    value: 'MR',
  },
  {
    name: 'Mauritius',
    numeric_code: '480',
    phone_code: '230',
    region_id: '1',
    value: 'MU',
  },
  {
    name: 'Mayotte',
    numeric_code: '175',
    phone_code: '262',
    region_id: '1',
    value: 'YT',
  },
  {
    name: 'Mexico',
    numeric_code: '484',
    phone_code: '52',
    region_id: '2',
    value: 'MX',
  },
  {
    name: 'Micronesia',
    numeric_code: '583',
    phone_code: '691',
    region_id: '5',
    value: 'FM',
  },
  {
    name: 'Moldova',
    numeric_code: '498',
    phone_code: '373',
    region_id: '4',
    value: 'MD',
  },
  {
    name: 'Monaco',
    numeric_code: '492',
    phone_code: '377',
    region_id: '4',
    value: 'MC',
  },
  {
    name: 'Mongolia',
    numeric_code: '496',
    phone_code: '976',
    region_id: '3',
    value: 'MN',
  },
  {
    name: 'Montenegro',
    numeric_code: '499',
    phone_code: '382',
    region_id: '4',
    value: 'ME',
  },
  {
    name: 'Montserrat',
    numeric_code: '500',
    phone_code: '+1-664',
    region_id: '2',
    value: 'MS',
  },
  {
    name: 'Morocco',
    numeric_code: '504',
    phone_code: '212',
    region_id: '1',
    value: 'MA',
  },
  {
    name: 'Mozambique',
    numeric_code: '508',
    phone_code: '258',
    region_id: '1',
    value: 'MZ',
  },
  {
    name: 'Myanmar',
    numeric_code: '104',
    phone_code: '95',
    region_id: '3',
    value: 'MM',
  },
  {
    name: 'Namibia',
    numeric_code: '516',
    phone_code: '264',
    region_id: '1',
    value: 'NA',
  },
  {
    name: 'Nauru',
    numeric_code: '520',
    phone_code: '674',
    region_id: '5',
    value: 'NR',
  },
  {
    name: 'Nepal',
    numeric_code: '524',
    phone_code: '977',
    region_id: '3',
    value: 'NP',
  },
  {
    name: 'Netherlands',
    numeric_code: '528',
    phone_code: '31',
    region_id: '4',
    value: 'NL',
  },
  {
    name: 'New Caledonia',
    numeric_code: '540',
    phone_code: '687',
    region_id: '5',
    value: 'NC',
  },
  {
    name: 'New Zealand',
    numeric_code: '554',
    phone_code: '64',
    region_id: '5',
    value: 'NZ',
  },
  {
    name: 'Nicaragua',
    numeric_code: '558',
    phone_code: '505',
    region_id: '2',
    value: 'NI',
  },
  {
    name: 'Niger',
    numeric_code: '562',
    phone_code: '227',
    region_id: '1',
    value: 'NE',
  },
  {
    name: 'Nigeria',
    numeric_code: '566',
    phone_code: '234',
    region_id: '1',
    value: 'NG',
  },
  {
    name: 'Niue',
    numeric_code: '570',
    phone_code: '683',
    region_id: '5',
    value: 'NU',
  },
  {
    name: 'Norfolk Island',
    numeric_code: '574',
    phone_code: '672',
    region_id: '5',
    value: 'NF',
  },
  {
    name: 'North Korea',
    numeric_code: '408',
    phone_code: '850',
    region_id: '3',
    value: 'KP',
  },
  {
    name: 'North Macedonia',
    numeric_code: '807',
    phone_code: '389',
    region_id: '4',
    value: 'MK',
  },
  {
    name: 'Northern Mariana Islands',
    numeric_code: '580',
    phone_code: '+1-670',
    region_id: '5',
    value: 'MP',
  },
  {
    name: 'Norway',
    numeric_code: '578',
    phone_code: '47',
    region_id: '4',
    value: 'NO',
  },
  {
    name: 'Oman',
    numeric_code: '512',
    phone_code: '968',
    region_id: '3',
    value: 'OM',
  },
  {
    name: 'Pakistan',
    numeric_code: '586',
    phone_code: '92',
    region_id: '3',
    value: 'PK',
  },
  {
    name: 'Palau',
    numeric_code: '585',
    phone_code: '680',
    region_id: '5',
    value: 'PW',
  },
  {
    name: 'Palestinian Territory Occupied',
    numeric_code: '275',
    phone_code: '970',
    region_id: '3',
    value: 'PS',
  },
  {
    name: 'Panama',
    numeric_code: '591',
    phone_code: '507',
    region_id: '2',
    value: 'PA',
  },
  {
    name: 'Papua New Guinea',
    numeric_code: '598',
    phone_code: '675',
    region_id: '5',
    value: 'PG',
  },
  {
    name: 'Paraguay',
    numeric_code: '600',
    phone_code: '595',
    region_id: '2',
    value: 'PY',
  },
  {
    name: 'Peru',
    numeric_code: '604',
    phone_code: '51',
    region_id: '2',
    value: 'PE',
  },
  {
    name: 'Philippines',
    numeric_code: '608',
    phone_code: '63',
    region_id: '3',
    value: 'PH',
  },
  {
    name: 'Pitcairn Island',
    numeric_code: '612',
    phone_code: '870',
    region_id: '5',
    value: 'PN',
  },
  {
    name: 'Poland',
    numeric_code: '616',
    phone_code: '48',
    region_id: '4',
    value: 'PL',
  },
  {
    name: 'Portugal',
    numeric_code: '620',
    phone_code: '351',
    region_id: '4',
    value: 'PT',
  },
  {
    name: 'Puerto Rico',
    numeric_code: '630',
    phone_code: '+1-787 and 1-939',
    region_id: '2',
    value: 'PR',
  },
  {
    name: 'Qatar',
    numeric_code: '634',
    phone_code: '974',
    region_id: '3',
    value: 'QA',
  },
  {
    name: 'Reunion',
    numeric_code: '638',
    phone_code: '262',
    region_id: '1',
    value: 'RE',
  },
  {
    name: 'Romania',
    numeric_code: '642',
    phone_code: '40',
    region_id: '4',
    value: 'RO',
  },
  {
    name: 'Russia',
    numeric_code: '643',
    phone_code: '7',
    region_id: '4',
    value: 'RU',
  },
  {
    name: 'Rwanda',
    numeric_code: '646',
    phone_code: '250',
    region_id: '1',
    value: 'RW',
  },
  {
    name: 'Saint Helena',
    numeric_code: '654',
    phone_code: '290',
    region_id: '1',
    value: 'SH',
  },
  {
    name: 'Saint Kitts and Nevis',
    numeric_code: '659',
    phone_code: '+1-869',
    region_id: '2',
    value: 'KN',
  },
  {
    name: 'Saint Lucia',
    numeric_code: '662',
    phone_code: '+1-758',
    region_id: '2',
    value: 'LC',
  },
  {
    name: 'Saint Pierre and Miquelon',
    numeric_code: '666',
    phone_code: '508',
    region_id: '2',
    value: 'PM',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    numeric_code: '670',
    phone_code: '+1-784',
    region_id: '2',
    value: 'VC',
  },
  {
    name: 'Saint-Barthelemy',
    numeric_code: '652',
    phone_code: '590',
    region_id: '2',
    value: 'BL',
  },
  {
    name: 'Saint-Martin (French part)',
    numeric_code: '663',
    phone_code: '590',
    region_id: '2',
    value: 'MF',
  },
  {
    name: 'Samoa',
    numeric_code: '882',
    phone_code: '685',
    region_id: '5',
    value: 'WS',
  },
  {
    name: 'San Marino',
    numeric_code: '674',
    phone_code: '378',
    region_id: '4',
    value: 'SM',
  },
  {
    name: 'Sao Tome and Principe',
    numeric_code: '678',
    phone_code: '239',
    region_id: '1',
    value: 'ST',
  },
  {
    name: 'Saudi Arabia',
    numeric_code: '682',
    phone_code: '966',
    region_id: '3',
    value: 'SA',
  },
  {
    name: 'Senegal',
    numeric_code: '686',
    phone_code: '221',
    region_id: '1',
    value: 'SN',
  },
  {
    name: 'Serbia',
    numeric_code: '688',
    phone_code: '381',
    region_id: '4',
    value: 'RS',
  },
  {
    name: 'Seychelles',
    numeric_code: '690',
    phone_code: '248',
    region_id: '1',
    value: 'SC',
  },
  {
    name: 'Sierra Leone',
    numeric_code: '694',
    phone_code: '232',
    region_id: '1',
    value: 'SL',
  },
  {
    name: 'Singapore',
    numeric_code: '702',
    phone_code: '65',
    region_id: '3',
    value: 'SG',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    numeric_code: '534',
    phone_code: '1721',
    region_id: '2',
    value: 'SX',
  },
  {
    name: 'Slovakia',
    numeric_code: '703',
    phone_code: '421',
    region_id: '4',
    value: 'SK',
  },
  {
    name: 'Slovenia',
    numeric_code: '705',
    phone_code: '386',
    region_id: '4',
    value: 'SI',
  },
  {
    name: 'Solomon Islands',
    numeric_code: '090',
    phone_code: '677',
    region_id: '5',
    value: 'SB',
  },
  {
    name: 'Somalia',
    numeric_code: '706',
    phone_code: '252',
    region_id: '1',
    value: 'SO',
  },
  {
    name: 'South Africa',
    numeric_code: '710',
    phone_code: '27',
    region_id: '1',
    value: 'ZA',
  },
  {
    name: 'South Georgia',
    numeric_code: '239',
    phone_code: '500',
    region_id: '2',
    value: 'GS',
  },
  {
    name: 'South Korea',
    numeric_code: '410',
    phone_code: '82',
    region_id: '3',
    value: 'KR',
  },
  {
    name: 'South Sudan',
    numeric_code: '728',
    phone_code: '211',
    region_id: '1',
    value: 'SS',
  },
  {
    name: 'Spain',
    numeric_code: '724',
    phone_code: '34',
    region_id: '4',
    value: 'ES',
  },
  {
    name: 'Sri Lanka',
    numeric_code: '144',
    phone_code: '94',
    region_id: '3',
    value: 'LK',
  },
  {
    name: 'Sudan',
    numeric_code: '729',
    phone_code: '249',
    region_id: '1',
    value: 'SD',
  },
  {
    name: 'Suriname',
    numeric_code: '740',
    phone_code: '597',
    region_id: '2',
    value: 'SR',
  },
  {
    name: 'Svalbard and Jan Mayen Islands',
    numeric_code: '744',
    phone_code: '47',
    region_id: '4',
    value: 'SJ',
  },
  {
    name: 'Sweden',
    numeric_code: '752',
    phone_code: '46',
    region_id: '4',
    value: 'SE',
  },
  {
    name: 'Switzerland',
    numeric_code: '756',
    phone_code: '41',
    region_id: '4',
    value: 'CH',
  },
  {
    name: 'Syria',
    numeric_code: '760',
    phone_code: '963',
    region_id: '3',
    value: 'SY',
  },
  {
    name: 'Taiwan',
    numeric_code: '158',
    phone_code: '886',
    region_id: '3',
    value: 'TW',
  },
  {
    name: 'Tajikistan',
    numeric_code: '762',
    phone_code: '992',
    region_id: '3',
    value: 'TJ',
  },
  {
    name: 'Tanzania',
    numeric_code: '834',
    phone_code: '255',
    region_id: '1',
    value: 'TZ',
  },
  {
    name: 'Thailand',
    numeric_code: '764',
    phone_code: '66',
    region_id: '3',
    value: 'TH',
  },
  {
    name: 'The Bahamas',
    numeric_code: '044',
    phone_code: '+1-242',
    region_id: '2',
    value: 'BS',
  },
  {
    name: 'Timor-Leste',
    numeric_code: '626',
    phone_code: '670',
    region_id: '3',
    value: 'TL',
  },
  {
    name: 'Togo',
    numeric_code: '768',
    phone_code: '228',
    region_id: '1',
    value: 'TG',
  },
  {
    name: 'Tokelau',
    numeric_code: '772',
    phone_code: '690',
    region_id: '5',
    value: 'TK',
  },
  {
    name: 'Tonga',
    numeric_code: '776',
    phone_code: '676',
    region_id: '5',
    value: 'TO',
  },
  {
    name: 'Trinidad and Tobago',
    numeric_code: '780',
    phone_code: '+1-868',
    region_id: '2',
    value: 'TT',
  },
  {
    name: 'Tunisia',
    numeric_code: '788',
    phone_code: '216',
    region_id: '1',
    value: 'TN',
  },
  {
    name: 'Turkey',
    numeric_code: '792',
    phone_code: '90',
    region_id: '3',
    value: 'TR',
  },
  {
    name: 'Turkmenistan',
    numeric_code: '795',
    phone_code: '993',
    region_id: '3',
    value: 'TM',
  },
  {
    name: 'Turks and Caicos Islands',
    numeric_code: '796',
    phone_code: '+1-649',
    region_id: '2',
    value: 'TC',
  },
  {
    name: 'Tuvalu',
    numeric_code: '798',
    phone_code: '688',
    region_id: '5',
    value: 'TV',
  },
  {
    name: 'Uganda',
    numeric_code: '800',
    phone_code: '256',
    region_id: '1',
    value: 'UG',
  },
  {
    name: 'Ukraine',
    numeric_code: '804',
    phone_code: '380',
    region_id: '4',
    value: 'UA',
  },
  {
    name: 'United Arab Emirates',
    numeric_code: '784',
    phone_code: '971',
    region_id: '3',
    value: 'AE',
  },
  {
    name: 'United Kingdom',
    numeric_code: '826',
    phone_code: '44',
    region_id: '4',
    value: 'GB',
  },
  {
    name: 'United States',
    numeric_code: '840',
    phone_code: '1',
    region_id: '2',
    value: 'US',
  },
  {
    name: 'United States Minor Outlying Islands',
    numeric_code: '581',
    phone_code: '1',
    region_id: '2',
    value: 'UM',
  },
  {
    name: 'Uruguay',
    numeric_code: '858',
    phone_code: '598',
    region_id: '2',
    value: 'UY',
  },
  {
    name: 'Uzbekistan',
    numeric_code: '860',
    phone_code: '998',
    region_id: '3',
    value: 'UZ',
  },
  {
    name: 'Vanuatu',
    numeric_code: '548',
    phone_code: '678',
    region_id: '5',
    value: 'VU',
  },
  {
    name: 'Vatican City State (Holy See)',
    numeric_code: '336',
    phone_code: '379',
    region_id: '4',
    value: 'VA',
  },
  {
    name: 'Venezuela',
    numeric_code: '862',
    phone_code: '58',
    region_id: '2',
    value: 'VE',
  },
  {
    name: 'Vietnam',
    numeric_code: '704',
    phone_code: '84',
    region_id: '3',
    value: 'VN',
  },
  {
    name: 'Virgin Islands (British)',
    numeric_code: '092',
    phone_code: '+1-284',
    region_id: '2',
    value: 'VG',
  },
  {
    name: 'Virgin Islands (US)',
    numeric_code: '850',
    phone_code: '+1-340',
    region_id: '2',
    value: 'VI',
  },
  {
    name: 'Wallis and Futuna Islands',
    numeric_code: '876',
    phone_code: '681',
    region_id: '5',
    value: 'WF',
  },
  {
    name: 'Western Sahara',
    numeric_code: '732',
    phone_code: '212',
    region_id: '1',
    value: 'EH',
  },
  {
    name: 'Yemen',
    numeric_code: '887',
    phone_code: '967',
    region_id: '3',
    value: 'YE',
  },
  {
    name: 'Zambia',
    numeric_code: '894',
    phone_code: '260',
    region_id: '1',
    value: 'ZM',
  },
  {
    name: 'Zimbabwe',
    numeric_code: '716',
    phone_code: '263',
    region_id: '1',
    value: 'ZW',
  },
];
